version: '3'
services:
  app:
    build: .
      
    ports:
      - 3000:3000
    environment: 
      - DB_HOST=localhost
      - DB_NAME=mesero
      - DB_PORT=5438
      - DB_PASSWORD=aeiou123
      - DB_USERNAME=postgres


